name: Deploy Production

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: deploy
        env:
          ZCLOUD_USER_TOKEN: ${{ secrets.ZCLOUD_USER_TOKEN }}
          ZCLOUD_ENV: ${{ secrets.ZCLOUD_ENV_PRODUCTION }}
        run: |
          curl -s https://gh.zcloud.ws/scripts/zcloud-install.sh | sh -
          ./zcloud deploy --user-token "${ZCLOUD_USER_TOKEN}" --env "${ZCLOUD_ENV_PRODUCTION}"